# Generated by Django 3.2.6 on 2021-08-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='demo',
        ),
    ]
