# Generated by Django 3.2.6 on 2021-09-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user')),
            ],
        ),
    ]
