# Generated by Django 3.2.6 on 2021-09-01 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authorid',
            new_name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 1, 6, 5, 35, 341947, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
