# Generated by Django 3.2.6 on 2021-09-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20210901_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.IntegerField(default=0),
        ),
    ]
