# Generated by Django 3.2.6 on 2021-09-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_article_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
