# Generated by Django 3.2.6 on 2021-09-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_article_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
