# Generated by Django 3.2.6 on 2021-09-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarurl',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
