# Generated by Django 3.2.6 on 2021-09-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_id', to='demo.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liking_id', to='demo.user'),
        ),
    ]
