# Generated by Django 3.2.6 on 2021-09-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20210904_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liking',
        ),
        migrations.AddField(
            model_name='like',
            name='articleid',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='demo.article'),
        ),
        migrations.AddField(
            model_name='like',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demo.user'),
        ),
    ]
