# Generated by Django 3.2.6 on 2021-09-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_auto_20210904_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='articleid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
