# Generated by Django 3.2.6 on 2021-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='这位博主有点懒，还没有写个人介绍哦 ~', max_length=1000),
        ),
    ]
