# Generated by Django 3.2.6 on 2021-09-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
