# Generated by Django 3.2.6 on 2021-09-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_auto_20210906_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('articleid', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
