# Generated by Django 3.2.6 on 2021-09-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='towhich',
            field=models.IntegerField(default=0),
        ),
    ]
