# Generated by Django 3.2.6 on 2021-09-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='towhich',
            field=models.CharField(default='', max_length=15),
        ),
    ]
